CREATE TABLE "SF_Activities" (
"PROCESS_ID"  INTEGER NOT NULL,
"ACTIVITY_ID"  TEXT(50) NOT NULL,
"Type"  TEXT(50) NOT NULL,
"Description"  TEXT(50),
"ReferenceActivity"  TEXT(50),
"Name"  TEXT(50) NOT NULL,
"Status"  TEXT(50),
"Owner"  TEXT(50),
"CatchType"  TEXT(50),
"NR_EXECUTED"  INTEGER NOT NULL DEFAULT 0,
"GRANTS"  BLOB,
"BEHAVIOUR"  BLOB,
"LOG"  BLOB,
"LOGS"  BLOB,
"REPORTS"  BLOB,
PRIMARY KEY ("PROCESS_ID", "ACTIVITY_ID")
);
